### ISSUE TITLE
recent Travis-CI builds on 2.13.x branch have been failing

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dist-smoketest#22]
for example, https://travis-ci.org/scala/scala-dist-smoketest/builds/390820336

```
java.lang.NoClassDefFoundError: sbt/ConsoleOut$
	at sbt.StandardMain$.<init>(Main.scala:62)
	at sbt.StandardMain$.<clinit>(Main.scala)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: sbt.ConsoleOut$
```

I had a hunch it might be a problem with the build cache, so I cleared the caches and lo and behold, https://travis-ci.org/scala/scala-dist-smoketest/builds/390869919 passed

but then also I did #21, just in case

**Comment by SethTisue** [comment]
let's see how https://travis-ci.org/scala/scala-dist-smoketest/builds/391063037 does

**Comment by SethTisue** [comment]
green, so, optimistically closing. fingers crossed
